# Generated by Django 2.0.6 on 2018-06-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onionsites',
            name='bodyscanned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='onionsites',
            name='onionscanned',
            field=models.IntegerField(default=0),
        ),
    ]
